### ISSUE TITLE
Getting Bad Substitution Error

### ISSUE THREAD

**Issue by GiJ03** [hihackthis/autoKNOXSS#2]
![image](https://github.com/hihackthis/autoKNOXSS/assets/57536491/92d3681e-4034-43dd-96d8-869d2e2e7973)

**Comment by hihackthis** [comment]
Hi GiJ03,

Thanks for your report :)

Can I see the content of the test.txt file? If not, does it not have some undesirable character in it?

One thing, if the file is in the same folder of the autoKNOXSS, you don't need to put the complete path (absolute path), just the name of the file, in this case, only test.txt. ;)

Hugs

**Comment by GiJ03** [comment]
Hi @hihackthis ,

Please find the contents of `test.txt` in the below screenshot:
<img width="560" alt="image" src="https://github.com/hihackthis/autoKNOXSS/assets/57536491/23b1609a-915a-4b74-99ed-767d2f421902">

Additionally, I tried giving only the filename as well, still the error persists:
<img width="673" alt="image" src="https://github.com/hihackthis/autoKNOXSS/assets/57536491/eadfb2b8-fa11-4b6f-a3c0-ab8b26c625e4">

**Comment by hihackthis** [comment]
Hi @GiJ03,

`The 1st line is of the target website and 2nd line of the file is blank.`

Ok, no problem with this, it's fine. :)

So, I got two URLs with the same parameter and I did the test here, and works fine, look:

![case2a](https://github.com/hihackthis/autoKNOXSS/assets/19677459/f6cceccf-0127-4c2e-af45-d769d73aa372)

As I said, everything works fine. :)

Please, access the autoKNOXSS folder and enter the command **git pull** to update the autoKNOXSS, repeat the test, and will see what happens.

Hugs

**Comment by GiJ03** [comment]
Hi @hihackthis ,

`Git Pull` says `Already up to date.`. Can you please share a quick video of this? I understand this video may contain your KnoXSS API as well, you may reset it once the video is made?

**Comment by hihackthis** [comment]
Hi @GiJ03,

`The reason behind the tool's functionality solely on Linux and its non-functionality on Mac.`

Did you install **jq** on your Mac?

`The rationale for the tool identifying Firewall interference even when attempting to access test websites.`

Look, this URL of the _Vulweb_ is a POST method and not GET, so we need to add the data POST, searchFor=bobo&goButton=go, inside another file (check autoKNOSS manual). ;)

Here,

![case4](https://github.com/hihackthis/autoKNOXSS/assets/19677459/c015d9e9-add5-4237-96fc-2602fa7f4556)

Try again the _Testfire_ website:

![case3](https://github.com/hihackthis/autoKNOXSS/assets/19677459/3db078b6-d97b-49af-a629-78283c0de9c3)

But I will check it.

Hugs

**Comment by GiJ03** [comment]
Hi @hihackthis ,

Yes, `jq` is installed in my Mac.
<img width="198" alt="image" src="https://github.com/hihackthis/autoKNOXSS/assets/57536491/f136caba-d615-48d0-a29c-ab8fc4641497">

And I again tried with `testfire` website. It still shows blocked by firewall.

**Comment by hihackthis** [comment]
Hi @GiJ03,

Great!

Sorry question again, but did you install **jq** on linux too? Because in my tests if we forget to install **jq** the output will be always _Firewall is blocking_.

If everything it's ok, refresh the KNOXSS API key and try again. :)

Hugs

**Comment by GiJ03** [comment]
Hi @hihackthis ,

Yes, you are right. After installing `jq` in Linux, I got the tool in working!! Thanks!

I guess now, the Linux part is sorted, the only question that remains is that the error still persists while running this in Mac.
`./autoKNOXSS.sh: line 468: ${opt_2^^}: bad substitution`

<img width="703" alt="image" src="https://github.com/hihackthis/autoKNOXSS/assets/57536491/f0dfce2d-24fc-4cc1-b036-ebd20ac9ca8f">

**Comment by hihackthis** [comment]
Hi @GiJ03,

Please, `git pull` and try again on your Mac.

Hugs

**Comment by anonhunter** [comment]
HI, I am also facing the same,
after your last step, still the same error.
<img width="595" alt="Screenshot 2023-08-22 at 2 06 14 AM" src="https://github.com/hihackthis/autoKNOXSS/assets/32389814/36a085cf-e27e-4dcd-832b-30b90ce7c8df">

**Comment by hihackthis** [comment]
Hi @GiJ03 and @anonhunter,

Please, `git pull` and try again.

Hugs

**Comment by anonhunter** [comment]
> Hi @GiJ03 and @anonhunter,
> 
> Please, `git pull` and try again.
> 
> Hugs


Hi, Still not working brother.

<img width="752" alt="Screenshot 2023-08-22 at 9 08 29 PM" src="https://github.com/hihackthis/autoKNOXSS/assets/32389814/54d141bb-a437-45f9-ad8c-6f9ad510f36a">

**Comment by hihackthis** [comment]
Hi @anonhunter,

Thanks, but the colors were fixed. :)

Please, run autoKNOXSS again but with this command:

`bash -x -v autoKNOXSS`

Paste and copy the error output, please.

Hugs

**Comment by hihackthis** [comment]
Hi @anonhunter,

I edited your post to be shorter. ;)

I think that the problem is the **^**, so I removed it now.

Again, `git pull` and try, please. :)

Hugs

**Comment by anonhunter** [comment]
<img width="981" alt="Screenshot 2023-08-23 at 12 09 51 AM" src="https://github.com/hihackthis/autoKNOXSS/assets/32389814/092f82f1-3870-4ce4-b089-6b25608b9597">

Hey It worked bro.
Hope to bother you for some advance help. 😝
Thank you 🙏🏻

**Comment by anonhunter** [comment]
<img width="615" alt="Screenshot 2023-08-23 at 1 32 05 AM" src="https://github.com/hihackthis/autoKNOXSS/assets/32389814/339f7648-4a28-4e10-8b54-bb7e0550aab0">
Can we do anything to it?

**Comment by hihackthis** [comment]
Hi @anonhunter,

Please, `git pull`, I fixed warn color.

`Can we do anything to it?`

Sorry, I didn't understand. Is it about what?

Hugs

**Comment by anonhunter** [comment]
firewall blocking

**Comment by hihackthis** [comment]
You can try Flash Mode or/and AFB :wink:

I will lock the topic :v:

Thanks :grin:
